version: "2"

services:
    pyweb:
       build: ./pyweb
       ports:
         - "8080"
       links:
           - pyspark
           - kafka
       networks:
           - front-end

    pyspark:
       build: ./pyspark/.
       hostname: pyspark
       links: 
           - kafka
       networks:
           - back-end
   
    kafka:
       image: blacktop/kafka
       ports: 
           - "9092:9092"
           - "2181:2181" 
       environment:
          - KAFKA_ADVERTISED_HOST_NAME=192.168.99.100
          - CONSUMER_THREADS=3
          - KAFKA_CREATE_TOPICS=tweet-topic:1:1,processed-topic:1:1 
 
       networks:
           - back-end
 
networks:
       front-end:
       back-end:
